trigger:
- main

pool:
  vmImage: macos-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- checkout: self
  fetchDepth: 1

resources:
  repositories:
    - repository: self

variables:
  system.debug: true
